from config import settings

CONTENT_TIER_LIMITED_MAX_WORDS = 150
CONTENT_TIER_PARTIAL_MAX_WORDS = 300
TAG_SIMILARITY_THRESHOLD = settings.TAG_SIMILARITY_THRESHOLD
REFRESH_INTERVAL_DAYS = 7
FEED_PAGE_SIZE = 12
